[package]
name = "RustCalc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.3"
serde = {version = "1.0.102", features = ["derive"]}
serde_derive = "1.0.102"
serde_json = "1.0.41"
